### ISSUE TITLE
ユーザーリクエストの作成

### ISSUE THREAD

**Issue by sakai1250** [jphacks/F_2208#127]
## TODO

- [x] sail artisan make:request UpdateUserRequest
  - [x] check function rules()
- [x] check validation rules

### 関連課題

---

### 親課題

---

#### 備考

---
